export const USER_ACTION_TYPES = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SIGN_UP_USER_START: 'SIGN_UP_USER_START',
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILED: 'SIGN_IN_FAILED',
    SIGN_OUT_USER: 'SIGN_OUT_USER'
}

export const { SET_CURRENT_USER,
               CHECK_USER_SESSION,
               SIGN_UP_USER_START,
               GOOGLE_SIGN_IN_START,
               EMAIL_SIGN_IN_START,
               SIGN_IN_SUCCESS,
               SIGN_IN_FAILED,
               SIGN_OUT_USER } = USER_ACTION_TYPES